version: '3.8'

services:
  sql_server_bootcamp:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_bootcamp
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Bootcamp1433!"
    restart: always